Repository loonl/kmu-cs-withUs-2021, pull requests merged in 2021-11, with the labels that each got.

#1 feat: initial firebase setting
  .firebaserc
  .gitignore
  firebase.json
  functions/.eslintrc.json
  functions/.gitignore
  functions/package-lock.json
  functions/package.json
  functions/src/Firebase/firebase.ts
  functions/src/index.ts
  functions/tsconfig.dev.json
  functions/tsconfig.json
Labels: feature

#2 feat: added test middleware & refactored file structure
  .nvmrc
  functions/.eslintrc.json
  functions/.gitignore
  functions/package-lock.json
  functions/package.json
  functions/src/config/firebase.ts
  functions/src/controllers/auth.controller.ts
  functions/src/index.ts
  functions/src/routes/auth.route.ts
Labels: feature

#3 refactor: applied microsoft style guide
  .nvmrc
  functions/.eslintrc.json
  functions/package-lock.json
  functions/package.json
  functions/src/controllers/auth.controller.ts
  functions/src/routes/auth.route.ts
  functions/src/utils/tokenHandler.ts
Labels: refactor

#4 refactor: updated file structure
  functions/src/controllers/auth.controller.ts
  functions/src/index.ts
  functions/src/routes/auth/index.ts
  functions/src/routes/index.ts
  functions/src/utils/tokenHandler.ts
Labels: refactor

#5 chore: modified feature creating user
  functions/src/controllers/auth.controller.ts
  functions/src/index.ts
Labels: chore

#7 chore: added empty templates
  .DS_Store
  .gitignore
  .idea/.gitignore
  .idea/.name
  .idea/compiler.xml
  .idea/misc.xml
  .nvmrc
  .settings/org.eclipse.buildship.core.prefs
  functions/.eslintrc.json
  functions/.gitignore
  functions/package.json
  functions/src/controllers/auth.controller.ts
  functions/src/controllers/post.controller.ts
  functions/src/routes/auth/index.ts
  functions/src/routes/index.ts
  functions/src/routes/post/index.ts
  functions/tsconfig.json
Labels: chore

#8 feat: getting user info
  functions/src/controllers/auth.controller.ts
  functions/src/utils/tokenHandler.ts
Labels: feature

#9 feat: added showing lists and tags
  app/src/main/java/com/with/us/ListItem.java
  app/src/main/java/com/with/us/ListItemAdapter.java
  app/src/main/java/com/with/us/ListTagAdapter.java
  app/src/main/res/layout/activity_list.xml
  app/src/main/res/layout/activity_list_item.xml
  app/src/main/res/layout/activity_list_tag.xml
Labels: feature

#10 feat: rename list and tag widgets
  app/src/main/java/com/with/us/ListItemAdapter.java
  app/src/main/java/com/with/us/ListTagAdapter.java
  app/src/main/res/drawable/ic_list_person.png
  app/src/main/res/drawable/ic_list_star.png
  app/src/main/res/layout/activity_list_item.xml
  app/src/main/res/layout/activity_list_tag.xml
Labels: feature, refactor

#12 refactor: modified the way of returning controller's response
  functions/package-lock.json
  functions/src/controllers/auth.controller.ts
  functions/src/controllers/post.controller.ts
Labels: refactor

#14 remove: remove useless fragments to use ListView instead
  app/src/main/java/com/with/us/MainActivity.java
  app/src/main/java/com/with/us/ui/gallery/GalleryFragment.java
  app/src/main/java/com/with/us/ui/slideshow/SlideshowFragment.java
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/menu/activity_main_drawer.xml
  app/src/main/res/navigation/mobile_navigation.xml
Labels: refactor

#15 feat: added Http client handler & refactored codes
  app/src/main/java/com/with/us/models/PostDetail.java
  app/src/main/java/com/with/us/models/Test.java
  app/src/main/java/com/with/us/models/UserInfo.java
  app/src/main/java/com/with/us/services/RetrofitService.java
  app/src/main/java/com/with/us/services/api/PostService.java
  app/src/main/java/com/with/us/services/api/TestService.java
  app/src/main/java/com/with/us/services/api/UserService.java
  app/src/main/java/com/with/us/services/auxiliary/ApiConstants.java
  app/src/main/java/com/with/us/services/auxiliary/RequestHelper.java
  functions/.eslintrc.json
  functions/src/controllers/auth.controller.ts
  functions/src/index.ts
Labels: feature, refactor

#17 feat: added missing implementation on signing up
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/with/us/RegisterActivityFragment.java
  app/src/main/res/layout/activity_register_fragment.xml
Labels: feature

#18 fix: removed unused function
  app/src/main/java/com/with/us/MainActivity.java
Labels: bug

#19 Sangmin
  app/src/main/java/com/with/us/ClublistItem.java
  app/src/main/java/com/with/us/ClublistItemAdapter.java
  app/src/main/java/com/with/us/ClublistTagAdapter.java
  app/src/main/res/drawable/ic_clublist_member.png
  app/src/main/res/drawable/ic_clublist_star.png
  app/src/main/res/layout/activity_clublist.xml
  app/src/main/res/layout/activity_clublist_item.xml
  app/src/main/res/layout/activity_clublist_tag.xml
Labels: refactor

#20 feat: added http & firebase client service
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/with/us/MainActivity.java
  app/src/main/java/com/with/us/RegisterActivity.java
  app/src/main/java/com/with/us/RegisterActivityFragment.java
  app/src/main/java/com/with/us/UserInfo.java
  app/src/main/java/com/with/us/UserInfoActivity.java
  app/src/main/java/com/with/us/UserInfoChangeActivity.java
  app/src/main/java/com/with/us/models/Comment.java
  app/src/main/java/com/with/us/models/UserInfo.java
  app/src/main/java/com/with/us/services/RetrofitService.java
  app/src/main/java/com/with/us/services/api/CommentService.java
  app/src/main/java/com/with/us/services/api/PostService.java
  app/src/main/java/com/with/us/services/api/TestService.java
  app/src/main/java/com/with/us/services/api/UserService.java
  app/src/main/java/com/with/us/services/auxiliary/RequestHelper.java
  app/src/main/java/com/with/us/utils/FirebaseHelper.java
  app/src/main/res/layout/nav_header_main.xml
  app/src/main/res/menu/main.xml
  functions/src/controllers/auth.controller.ts
  functions/src/utils/tokenHandler.ts
Labels: feature

#21 feat: getting post from firestore via cloud function
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/with/us/ClubListActivity.java
  app/src/main/java/com/with/us/ClubListItemAdapter.java
  app/src/main/java/com/with/us/ClublistItem.java
  app/src/main/java/com/with/us/ClublistTagAdapter.java
  app/src/main/java/com/with/us/LoginActivity.java
  app/src/main/java/com/with/us/MainActivity.java
  app/src/main/java/com/with/us/services/api/PostService.java
  app/src/main/res/layout/activity_clublist.xml
  app/src/main/res/layout/activity_clublist_item.xml
  functions/src/controllers/post.controller.ts
  functions/src/utils/tokenHandler.ts
Labels: feature

#23 feat: added creating post
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/with/us/ClubListActivity.java
  app/src/main/java/com/with/us/ClubListItemAdapter.java
  app/src/main/java/com/with/us/MainActivity.java
  app/src/main/java/com/with/us/PostFormActivity.java
  app/src/main/java/com/with/us/RegisterActivity.java
  app/src/main/java/com/with/us/UserInfoActivity.java
  app/src/main/java/com/with/us/UserInfoChangeActivity.java
  app/src/main/java/com/with/us/services/RetrofitService.java
  app/src/main/res/drawable/pencil.png
  app/src/main/res/drawable/rounded_edittext.xml
  app/src/main/res/layout/activity_clublist.xml
  app/src/main/res/layout/activity_post_form.xml
  app/src/main/res/layout/activity_user_info.xml
  app/src/main/res/layout/activity_user_info_change.xml
  app/src/main/res/layout/item_main_group.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  functions/src/controllers/auth.controller.ts
  functions/src/controllers/post.controller.ts
Labels: feature

#26 refactor: reformatted code style
  app/src/main/java/com/with/us/ClubListItemAdapter.java
  app/src/main/java/com/with/us/ClubListTagAdapter.java
  app/src/main/java/com/with/us/CommentReplyActivity.java
  app/src/main/java/com/with/us/ListCategoryAdapter.java
  app/src/main/java/com/with/us/MainActivity.java
  app/src/main/java/com/with/us/PostDetailActivity.java
  app/src/main/java/com/with/us/RegisterActivityFragment.java
  app/src/main/res/layout/activity_clublist.xml
  app/src/main/res/layout/activity_commentreply.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_postdetail.xml
  app/src/main/res/layout/activity_register.xml
  app/src/main/res/layout/activity_user_info.xml
  app/src/main/res/layout/activity_user_info_change.xml
  app/src/main/res/layout/app_bar_main.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_register.xml
  app/src/main/res/layout/item_clublist_item.xml
  app/src/main/res/layout/item_clublist_tag.xml
  app/src/main/res/layout/item_main_child.xml
  app/src/main/res/layout/item_main_group.xml
  app/src/main/res/layout/item_postdetail_comments.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: refactor

#27 feat: changed layout to recyclerView for reply function
  app/src/main/java/com/with/us/ListComments.java
  app/src/main/java/com/with/us/ListCommentsAdapter.java
  app/src/main/java/com/with/us/ListCommentsViewType.java
  app/src/main/java/com/with/us/PostDetailActivity.java
  app/src/main/res/layout/activity_postdetail.xml
  app/src/main/res/layout/item_postdetail_comments.xml
  app/src/main/res/layout/item_postdetail_replies.xml
  app/src/main/res/values/dimens.xml
Labels: feature

#30 feat: added comment & reply function in PostDetailActivity
  app/src/main/java/com/with/us/CommentReplyActivity.java
  app/src/main/java/com/with/us/ListCommentsAdapter.java
  app/src/main/java/com/with/us/PostDetailActivity.java
  app/src/main/res/layout/activity_commentreply.xml
  app/src/main/res/layout/item_postdetail_comments.xml
  app/src/main/res/layout/item_postdetail_replies.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: feature

#31 Sangmin
  app/src/main/res/drawable-v24/ic_main.png
  app/src/main/res/drawable/ic_clublist_member.png
  app/src/main/res/drawable/pencil.png
  app/src/main/res/drawable/side_nav_bar.xml
  app/src/main/res/layout/activity_clublist.xml
  app/src/main/res/layout/activity_init.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_user_info.xml
  app/src/main/res/layout/activity_user_info_change.xml
  app/src/main/res/layout/fragment_register.xml
  app/src/main/res/layout/item_clublist_item.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/themes.xml
Labels: feature

#32 feat: added splash screen animation
  app/src/main/java/com/with/us/InitActivity.java
  app/src/main/res/anim/bounce.xml
  app/src/main/res/anim/decelerate_in.xml
  app/src/main/res/anim/decelerate_out.xml
  app/src/main/res/anim/linear.xml
  app/src/main/res/layout/activity_init.xml
Labels: feature
